from src.epw.metadata import EPWMetadata


def build_epw_header(metadata: EPWMetadata):
    return [
        f"LOCATION,{metadata.city},,,{metadata.country},{metadata.source},"
        f"{metadata.latitude},{metadata.longitude},{metadata.timezone},{metadata.elevation}",
        "DESIGN CONDITIONS,0",
        "TYPICAL/EXTREME PERIODS,0",
        "GROUND TEMPERATURES,0",
        "HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0",
        "COMMENTS 1,Generated from processed climate data",
        "COMMENTS 2,Generated by EPW_trans",
        "DATA PERIODS,1,1,Data,Sunday,1/1,12/31",
    ]